//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControldeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambiosRequerimiento
    {
        public string creadoPor { get; set; }
        public string requerimiento { get; set; }
        public int versionReqVieja { get; set; }
        public int versionReqNueva { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentarios { get; set; }
        public string motivo { get; set; }
    
        public virtual Requerimiento Requerimiento1 { get; set; }
        public virtual Requerimiento Requerimiento2 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
