//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControldeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambiosRequerimiento
    {
        public string creadoPor { get; set; }
        public string requerimiento { get; set; }
        public int versionReqVieja { get; set; }
        public int versionReqNueva { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentarios { get; set; }
        public string motivo { get; set; }
    
        public virtual Requerimiento Requerimiento1 { get; set; }
        public virtual Requerimiento Requerimiento2 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
