
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControldeCambios.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Progreso_Sprint
{

    public System.DateTime fecha { get; set; }

    public string sprintProyecto { get; set; }

    public int sprintNumero { get; set; }

    public int puntos { get; set; }



    public virtual Sprint Sprint { get; set; }

}

}
