
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControldeCambios.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Proyecto_Equipo
{

    public string usuario { get; set; }

    public string proyecto { get; set; }

    public string tipo { get; set; }



    public virtual Proyecto Proyecto1 { get; set; }

    public virtual Usuario Usuario1 { get; set; }

    public virtual Tipo_Desarrollador Tipo_Desarrollador { get; set; }

}

}
