//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControldeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto_Equipo
    {
        public string usuario { get; set; }
        public string proyecto { get; set; }
        public string tipo { get; set; }
    
        public virtual Proyecto Proyecto1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Tipo_Desarrollador Tipo_Desarrollador { get; set; }
    }
}
