
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControldeCambios.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Requerimientos_Cri_Acep
{

    public string reqCodigo { get; set; }

    public int reqVersion { get; set; }

    public string criterio { get; set; }



    public virtual Requerimiento Requerimiento { get; set; }

}

}
