//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControldeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requerimiento()
        {
            this.CambiosRequerimientos = new HashSet<CambiosRequerimiento>();
            this.CambiosRequerimientos1 = new HashSet<CambiosRequerimiento>();
            this.Sprints = new HashSet<Sprint>();
        }
    
        public string codigo { get; set; }
        public int version { get; set; }
        public System.DateTime creadoEn { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public int prioridad { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> esfuerzo { get; set; }
        public string estado { get; set; }
        public string creadoPor { get; set; }
        public string solicitadoPor { get; set; }
        public string proyecto { get; set; }
        public int modulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambiosRequerimiento> CambiosRequerimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CambiosRequerimiento> CambiosRequerimientos1 { get; set; }
        public virtual Modulo Modulo1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sprint> Sprints { get; set; }
    }
}
