
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControldeCambios.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sprint_Modulos
{

    public int modulo { get; set; }

    public string proyecto { get; set; }

    public int sprint { get; set; }



    public virtual Modulo Modulo1 { get; set; }

    public virtual Sprint Sprint1 { get; set; }

}

}
