
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ControldeCambios.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sprint
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sprint()
    {

        this.Progreso_Sprint = new HashSet<Progreso_Sprint>();

        this.Sprint_Modulos = new HashSet<Sprint_Modulos>();

    }


    public string proyecto { get; set; }

    public int numero { get; set; }

    public System.DateTime fechaInicio { get; set; }

    public System.DateTime fechaFinal { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Progreso_Sprint> Progreso_Sprint { get; set; }

    public virtual Proyecto Proyecto1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sprint_Modulos> Sprint_Modulos { get; set; }

}

}
