//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControldeCambios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string nombre { get; set; }
        public string cedula { get; set; }
        public string id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
